vich_uploader:
  db_driver: orm

  mappings:
    posts:
      uri_prefix: /images/posts
      upload_destination: "%kernel.project_dir%/public/images/posts"

    users:
      uri_prefix: /images/users
      upload_destination: "%kernel.project_dir%/public/images/users"
